

-- REMOVE BURIAL ASSISTANCE (BA) AND MANDATORY DEDUCTIONS
DECLARE @EMPID NVARCHAR(50), 
@PERIODFROM DATE, 
@BAAMOUNT MONEY, 
@BAFOR NVARCHAR(200)

SET @EMPID='06-24-4990'
SET @PERIODFROM='2024-02-26'
SET @BAAMOUNT = 40
SET @BAFOR = ' '

UPDATE tbl_Payroll SET DOthers = DOthers - @BAAMOUNT 
WHERE EmpID=@EMPID AND PeriodFrom=@PERIODFROM
EXEC REGEN_PAYROLL_SELECTED @EMPID,@PERIODFROM

UPDATE tbl_OtherDetails SET OADet =  @BAFOR
WHERE EmpID=@EMPID AND DFrom=@PERIODFROM
DELETE FROM tbl_Details WHERE EmpID=@EMPID and [Description] LIKE '%WEEKLY DEDUCTION%' AND Number=0 AND DATE >=@PERIODFROM

-- -- REMOVING BA FOR SPECIFIC EMPLOYEE:
-- -- ABAYON, ELLUSFROIE - 02-22-4113
-- -- DU, KARINA - 35-22-3728
-- -- DEJEGA, DANIEL - 01-85-0007
-- SELECT * FROM tbl_OtherDetails WHERE EmpID='02-22-4113' AND DFrom='06-26-2023'
-- SELECT * FROM tbl_Details WHERE EmpID='01-85-0007' AND [Date]>='06-26-2023'