
DECLARE @DATEFROM DATE ='12-29-2021', @DATETO DATE ='12-29-2021',
@DEPARTMENT VARCHAR(100)='', @CATEGORY VARCHAR(100)='', @ITEMNAME VARCHAR(200)='', @STORE VARCHAR(10)=''

SELECT *,
CASE WHEN D.TYPE='AR Credit Memo' THEN (D.COST*D.[Quantity Sold])*-1 ELSE D.COST*D.[Quantity Sold] END  AS 'Total Cost',
D.[Total Sales]-(D.COST*D.[Quantity Sold]) AS 'Gross Profit',
CASE WHEN D.TYPE='AR Credit Memo' THEN (((D.[Total Sales]-(D.COST*D.[Quantity Sold]))/D.[Total Sales])*100)*-1 ELSE ((D.[Total Sales]-(D.COST*D.[Quantity Sold]))/D.[Total Sales])*100 END AS 'Profit Margin' 
FROM(

SELECT  T2.ItmsGrpNam AS 'Department',
T3.BPLID AS 'BRANCH ID',
CASE WHEN T3.isIns ='Y' THEN 'AR RESERVE' ELSE 'AR INVOICE' END AS 'TYPE',
T1.U_Category AS 'Category',
T0.DocEntry AS 'Transaction#',T5.Number,
T0.DocDate AS 'Posting Date',
t3.U_DocSeries AS 'Invoice No.',
CASE WHEN  T7.REFDOCNUM IS NULL AND T7.RTYPE ='AP'
THEN CONCAT('AP ',T7.DocEntry)
WHEN T7.RTYPE='PO' AND T7.RefDocNum IS NOT NULL
THEN CONCAT('AP ',T7.REFDOCNUM)
ELSE ''
END AS 'Reference',
CASE WHEN T7.RTYPE ='AP' AND T7.ISSUEDATE IS NULL
THEN CONVERT(VARCHAR(20),T7.ISSUEDATE,101)
WHEN T7.RTYPE='PO' AND T7.ISSUEDATE IS NOT NULL
THEN CONVERT(VARCHAR(20),T7.ISSUEDATE,101)
ELSE ''
END AS 'ReferenceDate',
T3.CardName AS 'Customer',
T4.CardFName AS 'Foreign Name',
T3.Comments AS 'Comments',
T0.ocrcode AS 'Whse',
T0.ItemCode AS 'Item Code',
T0.unitMsr AS 'unit',
T0.Dscription AS 'Description',
CASE WHEN 
--T0.Quantity<>T7.Quantity
(SELECT COUNT(ItemCode)FROM POR1 WHERE DocEntry=T7.DocEntry AND ItemCode=T7.ItemCode 
AND DOCENTRY NOT IN (SELECT BASEENTRY FROM PCH1 WHERE BaseType=22 AND ITEMCODE IS NOT NULL)) +
(SELECT COUNT(ItemCode)FROM PCH1 WHERE DocEntry=T7.DocEntry AND ItemCode=T7.ItemCode ) >1
THEN T7.Quantity - ISNULL((SELECT A1.QUANTITY FROM IGE21 A0
			INNER JOIN IGE1 A1 ON A0.DOCENTRY=A1.DOCENTRY
			WHERE A0.REFOBJTYPE =13 AND REFDOCNUM=T0.DOCENTRY AND ITEMCODE=T0.ITEMCODE),0)
ELSE T0.Quantity - ISNULL((SELECT A1.QUANTITY FROM IGE21 A0
			INNER JOIN IGE1 A1 ON A0.DOCENTRY=A1.DOCENTRY
			WHERE A0.REFOBJTYPE =13 AND REFDOCNUM=T0.DOCENTRY AND ITEMCODE=T0.ITEMCODE),0)

END AS 'Quantity Sold',
T0.U_GPBD AS 'Price Before Discount',
T0.PriceAfVAT AS 'Price After Discount',
T0.INMPrice AS 'Price After Discount(VAT-Ex)',
ISNULL(T7.INMPrice,T7.INMPrice)	AS 'COST',

T0.Price * CASE WHEN 

(SELECT COUNT(Quantity)FROM POR1 WHERE DocEntry=T7.DocEntry AND ItemCode=T7.ItemCode AND ObjType=T7.ObjType 
AND DOCENTRY NOT IN (SELECT BASEENTRY FROM PCH1 WHERE BaseType=22 AND ITEMCODE IS NOT NULL)) +
(SELECT COUNT(Quantity)FROM PCH1 WHERE DocEntry=T7.DocEntry AND ItemCode=T7.ItemCode AND ObjType=T7.ObjType ) >1
THEN T7.Quantity
ELSE T0.Quantity - ISNULL((SELECT A1.QUANTITY FROM IGE21 A0
			INNER JOIN IGE1 A1 ON A0.DOCENTRY=A1.DOCENTRY
			WHERE A0.REFOBJTYPE =13 AND REFDOCNUM=T0.DOCENTRY AND ITEMCODE=T0.ITEMCODE),0)

END AS 'Total Sales'

FROM INV1 T0

INNER JOIN OITM T1 ON T0.ItemCode = T1.ItemCode
INNER JOIN OITB T2 ON T1.ItmsGrpCod = T2.ItmsGrpCod
INNER JOIN OINV T3 ON T0.DocEntry = T3.DocNum
INNER JOIN OCRD T4 ON T3.CardCode = T4.CardCode
INNER JOIN OJDT T5 ON T0.DocEntry=T5.BaseRef AND T5.TransType =13

INNER JOIN (SELECT DISTINCT A1.DOCENTRY,A0.RefObjType,A0.REFDOCNUM,A0.DOCENTRY AS 'REF_ENTRY',A0.ISSUEDATE,A1.INMPrice,A1.ItemCode,A1.ObjType,A1.Quantity,'PO' AS 'RTYPE'
			FROM RDR21 A0
			INNER JOIN PRQ1 A1 ON A0.RefDocNum=A1.DocEntry
			INNER JOIN POR1 A1 ON A0.RefDocNum=A1.DocEntry
			INNER JOIN POR1 A1 ON A0.RefDocNum=A1.DocEntry
			WHERE RefObjType=22 AND A1.DocEntry NOT IN (SELECT BASEENTRY FROM PCH1 WHERE BaseType=22 AND ITEMCODE IS NOT NULL)
			UNION ALL
			SELECT DISTINCT A2.DOCENTRY,A0.RefObjType,A0.REFDOCNUM,A0.DOCENTRY AS 'REF_ENTRY',A0.ISSUEDATE,A2.INMPrice,A2.ItemCode,A2.ObjType,A2.Quantity,'AP' AS 'RTYPE'
			FROM RDR21 A0
			INNER JOIN POR1 A1 ON A0.RefDocNum=A1.DocEntry
			INNER JOIN PCH1 A2 ON A1.DocEntry=A2.BaseEntry
			WHERE RefObjType=22) 
		AS T7
		ON T0.DocEntry=T7.REF_ENTRY AND T7.ItemCode=T0.ItemCode


WHERE T3.DocType = 'I' 
AND T1.ItemType='I'
AND T3.DocDate >= @DATEFROM AND T3.DocDate <= @DATETO
AND T3.CANCELED='N'
AND T3.U_BO_DSDD ='Y' OR T3.U_BO_DSDV ='Y' OR T3.U_BO_DSPD ='Y' OR T3.U_BO_DRS ='Y'

) D
WHERE D.[Quantity Sold]<>0
AND D.[BRANCH ID] NOT IN (SELECT BPLId FROM OBPL WHERE U_isDC='Y')
AND D.Department LIKE '%'+@DEPARTMENT+'%' 
AND D.Category LIKE '%'+@CATEGORY+'%'
AND D.Description LIKE '%'+@ITEMNAME+'%'
AND D.Whse LIKE '%'+@STORE+'%'
ORDER BY 'Transaction#' ASC