SELECT * FROM OJDT T0
LEFT JOIN VPM2 T1 ON T1.DOCENTRY=T0.Number AND TRANSCODE='OBB'

WHERE T1.DOCENTRY IS NULL


SELECT * FROM JDT1 WHERE TransId =4831


SELECT StornoToTr,* FROM OJDT WHERE NUMBER =12234

SELECT T1.DocNum,NUMBER,U_GrossAmt,SumApplied,T1.U_WTax,U_WTaxPay,CardName,DocDate,T0.TaxDate
,T0.REF1,T00.AccOUNT,T00.DEBIT,T00.CREDIT
FROM OJDT T0
INNER JOIN JDT1 T00 ON T0.NUMBER=T00.TRANSID
LEFT JOIN VPM2 T1 ON T1.DOCENTRY=T0.NUMBER AND T1.InvType=30
LEFT JOIN OVPM T2 ON T2.DOCNUM = T1.DOCNUM
WHERE T0.TRANSCODE='OBB'
AND T0.StornoToTr IS NULL
AND T0.NUMBER NOT IN (SELECT StornoToTr FROM OJDT WHERE StornoToTr IS NOT NULL)
AND T0.NUMBER IN (
SELECT TransId FROM JDT1 WHERE ShortName IN (SELECT CardCode FROM OCRD WHERE CARDTYPE='S'))

