
DECLARE @EMPID NVARCHAR(50), @PERIODFROM DATE, @AMOUNT MONEY, @DESC NVARCHAR(200)

SET @EMPID='01-24-0445'
SET @PERIODFROM='02-26-2024'
SET @AMOUNT = 0.00
-- SET @DESC = 'Allowance=' + CAST(@AMOUNT as nvarchar(100))

UPDATE tbl_Payroll SET Holiday=@AMOUNT WHERE PeriodFrom=@PERIODFROM AND EmpID=@EMPID
-- UPDATE tbl_OtherDetails SET OSDet= REPLACE(OSDet,'423.115',@AMOUNT) WHERE DFrom=@PERIODFROM AND EmpID=@EMPID
-- UPDATE tbl_OtherDetails SET OSDet= CONCAT('Allowance=',@AMOUNT) WHERE DFrom=@PERIODFROM AND EmpID=@EMPID

EXEC REGEN_PAYROLL_SELECTED @EMPID,@PERIODFROM