SELECT

T0.DOCDATE AS 'Document Date',
T0.PRFID AS 'PRFID',
T3.COMPCODE AS 'Company Code',
T3.COMPNAME AS 'Company Name',
T0.TOTAL AS 'Total',
T1.INVREF AS 'Invoice Number',
T1.INVDATE AS 'Invoice Date',
T1.INVAMT AS 'Invoice Amount'

FROM TBL_PRFHEADER T0

INNER JOIN TBL_PRFDETAILS T1 
ON T0.PRFID = T1.PRFID
INNER JOIN TBL_SUPPLIER T2
ON T0.SUPPID = T2.SUPPID
INNER JOIN TBL_COMPANY T3
ON T0.COMPID = T3.COMPID

WHERE 
T1.INPUTTAX > 0 AND
T0.IIFSTAT LIKE '%EXPORTED%' AND
T3.GROUPING = 'SOD'
ORDER BY T0.PRFID ASC

select * from tbl_prfdetails