SELECT* FROM tbl_Queue
WHERE CALLED <> 3

SELECT T0.TicketNum, CONVERT(DATE, T0.TICKETDATE) AS DATE, CONVERT(time, T0.TICKETDATE) AS TIME, T1.TransType FROM tbl_Ticket T0
LEFT JOIN tbl_TransactionType T1 ON T0.TransType = T1.ID
WHERE CONVERT(DATE, T0.TICKETDATE) =CONVERT(DATE, GETDATE())
