
DECLARE 
-- @DATEFROM DATE ={?dateFrom}, 
-- @DATETO DATE ={?dateTo},
-- @DEPARTMENT VARCHAR(100)='{?Department}',
-- @CATEGORY VARCHAR(100)='{?Category}',
-- @ITEMNAME VARCHAR(100)='{?ItemName}',
-- @STORE VARCHAR(20)='{?Whse}'
-- @USER VARCHAR(20)='spt1'

@DATEFROM  DATE='2024-01-01', 
@DATETO  DATE='2024-01-31',
@DEPARTMENT VARCHAR(100)='',
@CATEGORY VARCHAR(100)='',
@ITEMNAME VARCHAR(100)='',
@STORE VARCHAR(20)='dcc'
-- @USER VARCHAR(20)='SPT1'


EXECUTE  [dbo].[SP_SaleReportPerItemAP_By_AC] @DATEFROM,@DATETO,@DEPARTMENT,@CATEGORY,@ITEMNAME,@STORE,'SPT1'



