SELECT
T0.DOCNUM AS 'Document Number',
T0.DOCDATE AS 'Document Date',
T0.DOCDUEDATE AS 'Document Due Date',
T0.CARDCODE AS 'Vendor ID',
T0.SUPPNAME AS 'Supplier Name',
T0.AGENTCODE AS 'Agent ID',
T0.AGENTNAME AS 'Agent Name',

T1.ITEMCODE AS 'Item Code',
T1.DSCRIPTION AS 'Item Description',
T1.QUANTITY AS 'Quantity',
T1.PRICEFOB AS 'Price(W/O COST)',
T1.PRICEATWH AS 'Price(W/ COST)',

T1.PRICEFOB * T1.QUANTITY AS 'Total (W/O COST * QUANTITY)',
T1.PRICEATWH * T1.QUANTITY AS 'Total (W/COST * QUANTITY)',

T1.WHSCODE AS 'Store',

T0.DOCTOTAL AS 'Document Total',
T0.COSTSUM AS 'Cost Summary',
T0.DESCR AS 'Description'
FROM OIPF T0

INNER JOIN IPF1 T1 ON T0.DOCNUM = T1.DOCENTRY

WHERE 
CANCELED = 'N'

SELECT * FROM IPF3
