--SELECT 
 
--T0.ITEMCODE AS 'Item Code',
--T0.ITEMNAME AS 'Item Name',
--T0.ITEMTYPE AS 'Item Type',
--T0.ITMSGRPCOD AS 'Item Group Code',
--T0.UGPENTRY AS 'Item UOM Group',
--T0.VALIDFOR

--FROM OITM T0
--WHERE T0.ITEMNAME LIKE '%DRAGONPLY MARINE PLYWOOD 9MM 4%' 


--and t0.validfor <> 'Y'

--SELECT 
--ITEMNAME AS 'ITEMNAME',
--COUNT(*)
--FROM OITM
--GROUP BY
--ITEMNAME
--HAVING
--COUNT(*) > 1

--SELECT 
 
--T0.ITEMCODE AS 'Item Code',
--T0.ITEMNAME AS 'Item Name',
--T0.VALIDFOR

--FROM OITM T0
--WHERE T0.ITEMNAME LIKE '%WINDOW HINGES RIGHT STEEL%' 