
SELECT
T0.Docdate,
CASE WHEN T0.DocDate >= DATEADD(mm, DATEDIFF(mm, 0, '01/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))), 0)
AND T0.DocDate <= DATEADD (dd, -1, DATEADD(mm, DATEDIFF(mm, 0, '03/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))) + 1, 0)) THEN FORMAT(DATEADD(mm, DATEDIFF(mm, 0, '01/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))), 0),'   MM      dd      yy') + SPACE(70) + FORMAT(DATEADD (dd, -1, DATEADD(mm, DATEDIFF(mm, 0, '03/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))) + 1, 0)),'   MM    dd      yy') 
WHEN T0.DocDate >= DATEADD(mm, DATEDIFF(mm, 0, '04/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))), 0)
AND T0.DocDate <= DATEADD (dd, -1, DATEADD(mm, DATEDIFF(mm, 0, '06/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))) + 1, 0)) THEN FORMAT(DATEADD(mm, DATEDIFF(mm, 0, '04/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))), 0),'  MM      dd      yy') + SPACE(54) + FORMAT(DATEADD (dd, -1, DATEADD(mm, DATEDIFF(mm, 0, '06/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))) + 1, 0)),'   MM    dd      yy') 
WHEN T0.DocDate >= DATEADD(mm, DATEDIFF(mm, 0, '07/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))), 0)
AND T0.DocDate <= DATEADD (dd, -1, DATEADD(mm, DATEDIFF(mm, 0, '09/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))) + 1, 0)) THEN FORMAT(DATEADD(mm, DATEDIFF(mm, 0, '07/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))), 0),'   MM      dd      yy') + SPACE(54) + FORMAT(DATEADD (dd, -1, DATEADD(mm, DATEDIFF(mm, 0, '09/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))) + 1, 0)),'   MM    dd      yy') 
WHEN T0.DocDate >= DATEADD(mm, DATEDIFF(mm, 0, '07/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))), 0)
AND T0.DocDate <= DATEADD (dd, -1, DATEADD(mm, DATEDIFF(mm, 0, '09/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))) + 1, 0)) THEN FORMAT(DATEADD(mm, DATEDIFF(mm, 0, '10/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))), 0),'   MM      dd      yy') + SPACE(54) + FORMAT(DATEADD (dd, -1, DATEADD(mm, DATEDIFF(mm, 0, '12/01/' + CONVERT(VARCHAR(10),YEAR(GETDATE()))) + 1, 0)),'   MM    dd      yy') 
END AS WtaxPeriod,
T0.CardCode ,T0.CardName, T0.DocDate , 
(SELECT LEFT(LicTradNum, 3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) As 'P1stTIN',
(SELECT SUBSTRING(LicTradNum,5,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) As 'P2ndTIN',
(SELECT SUBSTRING(LicTradNum,9,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) As 'P3rdTIN',
(SELECT SUBSTRING(LicTradNum,13,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) As 'P4thTIN', 
T0.DocTotal, 
TaxbleAmnt,
T0.WTSum, T0.U_WTax,  

CASE WHEN T0.DOCTYPE = 'I' THEN
(Select Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT Distinct WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT Distinct OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END AS 'PY1stTIN',

CASE WHEN T0.DOCTYPE = 'I' THEN
(Select SUBSTRING(FedTaxID,5,3) FROM OWHS WHERE WhsCode=(SELECT Distinct WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select SUBSTRING(FedTaxId,5,3) FROM OWHS WHERE WhsCode=(SELECT Distinct OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END AS 'PY2ndTIN',

CASE WHEN T0.DOCTYPE = 'I' THEN
(Select SUBSTRING(FedTaxID,9,3) FROM OWHS WHERE WhsCode=(SELECT Distinct WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select SUBSTRING(FedTaxId,9,3) FROM OWHS WHERE WhsCode=(SELECT Distinct OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END AS 'PY3ndTIN',

CASE WHEN T0.DOCTYPE = 'I' THEN
(Select SUBSTRING(FedTaxID,13,3) FROM OWHS WHERE WhsCode=(SELECT Distinct WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select SUBSTRING(FedTaxId,13,3) FROM OWHS WHERE WhsCode=(SELECT Distinct OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END AS 'PY4thTIN',

(SELECT TI.U_ATCDesc FROM OWHT TI WHERE TI.WTCode = T1.WTCode) AS 'ATC Description', UPPER((SELECT DISTINCT CONCAT(CAST(Building AS varchar(max)),
(CASE WHEN Building IS NULL THEN '' ELSE ' ' END),Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END), StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],
(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) 
FROM CRD1 WHERE CardCode = t0.CardCode)) AS 'Payee Address',(Select CompnyName from OADM) AS Payor ,


CASE WHEN T0.DOCTYPE = 'I' THEN
UPPER((SELECT DISTINCT CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(SELECT Distinct WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum) )) 
WHEN T0.DOCTYPE = 'S' THEN
UPPER((SELECT DISTINCT CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(
SELECT Distinct OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum) )) 
 END AS 'PayorAddress',


CASE WHEN T0.DOCTYPE = 'I' THEN
(SELECT ZipCode FROM owhs  WHERE WhsCode=(SELECT Distinct WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(SELECT ZipCode FROM owhs  WHERE WhsCode=(SELECT Distinct OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) 
END AS 'PayorZipCode',

( SELECT DISTINCT ZipCode FROM CRD1 WHERE CardCode = T0.CardCode) AS 'PayeeZipCode',

(SELECT COUNT(*) from PDF2 T6 WHERE T6.DOCNUM = 328) AS 'ROWS'

FROM OPCH T0 INNER JOIN PCH5 T1 ON T0.DocNum = T1.AbsEntry 
INNER JOIN PDF2 ON T0.Docentry = PDF2.Docentry WHERE PDF2.DocNum = 328
ORDER BY T0.DOCENTRY ASC
OFFSET 0 ROWS FETCH NEXT 15 ROWS ONLY
