SELECT 
T2.NUMBER,
T2.BASEREF,
T0.DEBIT,
T0.CREDIT,
T1.ACCTCODE,
T1.ACCTNAME
FROM JDT1 T0 
INNER JOIN OACT T1 ON T0.ACCOUNT = T1.ACCTCODE
INNER JOIN OJDT T2 ON T2.NUMBER = T0.TRANSID
WHERE T1.ACCTNAME LIKE '%NOT INVOICED%' AND T0.DEBIT > 0
ORDER BY T2.BASEREF ASC


816
780