
SELECT 
T2.NUMBER AS 'JE Number',
T1.TRANSTYPE as 'Transaction Type',

CASE 
WHEN T1.TRANSTYPE = 30 THEN 'Manual JE'
WHEN  T1.TRANSTYPE = 14 THEN 'A/R CM'
WHEN T1.TRANSTYPE = 13 THEN 'A/R Invoice'
WHEN T1.TRANSTYPE = 18 THEN 'A/P Invoice'
WHEN T1.TRANSTYPE = 69 THEN 'Landed Costs'
WHEN T1.TRANSTYPE = 59 THEN 'Goods Receipt'
WHEN T1.TRANSTYPE = 60 THEN 'Goods Issue'
WHEN T1.TRANSTYPE = 162 THEN 'Inventory Revalution'
WHEN T1.TRANSTYPE = 15 THEN 'Deliveries'
WHEN T1.TRANSTYPE = 19 THEN 'A/P CM'
WHEN T1.TRANSTYPE = 1470000071 THEN 'Depreciation Run'
WHEN T1.TRANSTYPE = 24 THEN 'Incoming Payments'
WHEN T1.TRANSTYPE = -4 THEN 'Interest Income'
WHEN T1.TRANSTYPE = 25 THEN 'Deposit' 

END AS 'Document Type',

T1.BASEREF AS 'Document Number',
T2.MEMO AS 'JE Remarks',
T0.ACCTCODE AS 'Account Code',
T0.ACCTNAME AS 'Account Name',
T1.DEBIT,
T1.CREDIT,
T1.PROFITCODE AS 'Store Performance',
T1.OCRCODE2 AS 'Expenses by Funtion'
FROM OACT T0
INNER JOIN JDT1 T1 ON T0.ACCTCODE = T1.ACCOUNT
INNER JOIN OJDT T2 ON T1.TRANSID = T2.NUMBER

WHERE (T0.FATHERNUM LIKE '%OE%' AND (T1.PROFITCODE IS NULL OR T1.PROFITCODE = '') AND 

'N' = CASE 
WHEN T1.TRANSTYPE = 30 THEN 'N'
WHEN T1.TRANSTYPE = 13 THEN (SELECT T3.CANCELED FROM OINV T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 14 THEN (SELECT T3.CANCELED FROM ORIN T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 15 THEN (SELECT T3.CANCELED FROM ODLN T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 19 THEN (SELECT T3.CANCELED FROM ORPC T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 24 THEN (SELECT T3.CANCELED FROM orct T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 18 THEN (SELECT T3.CANCELED FROM OPCH T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
ELSE 'N'
END)

OR

(T0.FATHERNUM LIKE '%OE%' AND (T1.OCRCODE2 IS NULL OR T1.OCRCODE2 = '') AND 

'N' = CASE 
WHEN T1.TRANSTYPE = 30 THEN 'N'
WHEN T1.TRANSTYPE = 13 THEN (SELECT T3.CANCELED FROM OINV T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 14 THEN (SELECT T3.CANCELED FROM ORIN T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 15 THEN (SELECT T3.CANCELED FROM ODLN T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 19 THEN (SELECT T3.CANCELED FROM ORPC T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 24 THEN (SELECT T3.CANCELED FROM orct T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
WHEN T1.TRANSTYPE = 18 THEN (SELECT T3.CANCELED FROM OPCH T3 WHERE T3.CANCELED = 'N' AND T1.BASEREF = T3.DOCNUM)
ELSE 'N'
END)

ORDER BY T1.TRANSTYPE, T1.BASEREF ASC

