

-- SELECT DISTINCT Dscription,ItemCode FROM INV1 WHERE Dscription LIKE '%REPUBLIC PORTLAND%'



DECLARE @DATEFROM AS DATE ='01-01-2021', @DATETO  AS DATE ='07-31-2022',
@DEPARTMENT VARCHAR(100)='', @CATEGORY VARCHAR(100)='', @ITEMNAME VARCHAR(200)='REPUBLIC PORTLAND', @STORE VARCHAR(10)=''


SELECT D.*,
CASE WHEN D.[DE-AP]<>0 
THEN convert(varchar(20),OJDT.Number)
WHEN TYPE='AR RESERVE' AND (SELECT COUNT(BASEENTRY) FROM DLN1 WHERE BaseEntry=D.Transaction# AND DLN1.ItemCode=D.[Item Code])=0
THEN CONCAT('AR - ',D.Transaction# )
ELSE convert(varchar(20),D.Number)
END AS 'JE-COST',

CASE WHEN D.TYPE='AR Credit Memo' 
	THEN (D.COST*D.[Quantity Sold])*-1 
	ELSE D.COST*D.[Quantity Sold] 
END  AS 'Total Cost',

CASE WHEN D.SWW='FREEBIES' AND D.[Total Sales]=0 
	THEN 0 
	ELSE 
		CASE WHEN D.TYPE='AR Credit Memo' 
		THEN D.[Total Sales]-((D.COST*D.[Quantity Sold])*-1)
		ELSE D.[Total Sales]-(D.COST*D.[Quantity Sold]) 
		END
END AS 'Gross Profit',

CASE WHEN D.SWW='FREEBIES' AND D.[Total Sales]=0 
	THEN 0 
	ELSE 
		CASE WHEN D.TYPE='AR Credit Memo' 
		THEN (((D.[Total Sales]-((D.COST*D.[Quantity Sold])*-1))/NULLIF(D.[Total Sales], 0))*100)*-1 
		ELSE ((D.[Total Sales]-(D.COST*D.[Quantity Sold]))/NULLIF(D.[Total Sales], 0))*100 
		END 
END AS 'Profit Margin' 


FROM(


SELECT T2.ItmsGrpNam AS 'Department',T3.CANCELED,T1.SWW,
CASE WHEN T5.RTYPE='AP' 
THEN T5.DocEntry
WHEN T6.RTYPE='AP' THEN T6.DOCENTRY
WHEN T7.RTYPE='AP' THEN T7.DocEntry
WHEN T8.DocEntry IS NOT NULL THEN T8.DocEntry
END AS 'DE-AP',
CASE WHEN ISNULL(ISNULL(T5.INMPrice,ISNULL(T6.INMPrice,T7.INMPrice)),T8.INMPrice) IS NOT NULL THEN 18 ELSE 0 END AS 'TRANSTYPE',
T3.BPLID AS 'BRANCH ID',
'DROPSHIP' AS 'TYPE',
T1.U_Category AS 'Category',
T0.DocEntry AS 'Transaction#',T10.Number,
T3.DocDate AS 'Posting Date',
t3.U_DocSeries AS 'Invoice No.',
CASE 
	WHEN  T5.DocEntry IS NOT NULL AND T5.RTYPE ='AP'
	THEN CONCAT('AP ',T5.DocEntry)
	WHEN T6.RTYPE='AP' AND T6.RefDocNum IS NOT NULL
	THEN CONCAT('AP ',T6.REFDOCNUM)
	WHEN T8.DocEntry IS NOT NULL 
	THEN CONCAT('AP ',T8.DocEntry)
	WHEN T7.DocEntry IS NOT NULL AND T7.RTYPE='AP'
	THEN CONCAT('AP ',T7.DocEntry)
	ELSE ''
END AS 'Reference',
CASE 
	WHEN T5.RTYPE ='AP' AND T5.TAXDATE IS NOT NULL
	THEN CONVERT(VARCHAR(20),T5.TAXDATE,101)
	WHEN T6.RTYPE='AP' AND T6.ISSUEDATE IS NOT NULL
	THEN CONVERT(VARCHAR(20),T6.ISSUEDATE,101)
	WHEN T8.TaxDate IS NOT NULL 
	THEN CONVERT(VARCHAR(20),T8.TAXDATE,101)
	WHEN T7.IssueDate IS NOT NULL AND T7.RTYPE='AP'
	THEN CONVERT(VARCHAR(20),T7.IssueDate,101)
	ELSE t7.IssueDate
END AS 'ReferenceDate',
T3.CardName AS 'Customer',
T4.CardFName AS 'Foreign Name',
CASE 
	WHEN T9.Number IS NULL 
	THEN T3.Comments
	ELSE
	CONCAT(T3.Comments,' ; LC: ',T9.Number) 
END AS 'Comments',
T0.ocrcode AS 'Whse',
T0.ItemCode AS 'Item Code',
T0.unitMsr AS 'unit',
T0.Dscription AS 'Description',
T0.Quantity - ISNULL(T11.Quantity,0)
AS 'Quantity Sold',   
T0.U_GPBD AS 'Price Before Discount',
T0.PriceAfVAT AS 'Price After Discount',
T0.INMPrice AS 'Price After Discount(VAT-Ex)',

CASE 
	WHEN T5.INMPrice IS NULL AND T6.INMPrice IS NOT NULL AND T7.INMPrice IS NULL AND T8.INMPrice IS NULL
	THEN T6.INMPrice + ISNULL(((T0.INMPrice*(T0.Quantity - ISNULL(T11.Quantity,0))/T12.[SALES SUM])*T6.[LANDEDCOST])/T0.Quantity - ISNULL(T11.Quantity,0),0)
	WHEN T5.INMPrice IS NULL AND T6.INMPrice IS  NULL AND T7.INMPrice IS NOT NULL AND T8.INMPrice IS NULL
	THEN T7.INMPrice + ISNULL(((T0.INMPrice*(T0.Quantity - ISNULL(T11.Quantity,0))/T12.[SALES SUM])*T7.[LANDEDCOST])/T0.Quantity - ISNULL(T11.Quantity,0),0)
	WHEN T5.INMPrice IS NULL AND T6.INMPrice IS  NULL AND T7.INMPrice IS NULL AND T8.INMPrice IS NOT NULL
	THEN T8.INMPrice + ISNULL(((T0.INMPrice*(T0.Quantity - ISNULL(T11.Quantity,0))/T12.[SALES SUM])*T9.[LANDEDCOST])/T0.Quantity - ISNULL(T11.Quantity,0),0)
	ELSE T5.INMPrice + ISNULL(((T0.INMPrice*(T0.Quantity - ISNULL(T11.Quantity,0))/T12.[SALES SUM])*T5.[LANDEDCOST])/T0.Quantity - ISNULL(T11.Quantity,0),0)
END AS 'COST',
t5.INMPrice as t5,t6.INMPrice as t6,t7.INMPrice as t7,t8.INMPrice as t8,

T0.INMPrice*T0.Quantity - ISNULL(T11.Quantity,0)
AS 'Total Sales'

FROM INV1 T0
INNER JOIN OITM T1 ON T0.ItemCode = T1.ItemCode
INNER JOIN OITB T2 ON T1.ItmsGrpCod = T2.ItmsGrpCod
INNER JOIN OINV T3 ON T0.DocEntry = T3.DocNum
INNER JOIN OCRD T4 ON T3.CardCode = T4.CardCode
--from SO TO AP LINK NOT BROKEN
LEFT JOIN (	
			SELECT DISTINCT A2.INMPrice,A2.DocEntry,A2.BaseEntry,A2.Quantity,A2.ItemCode,A2.WhsCode,A2.ObjType,A3.TAXDATE,'PO'AS 'RTYPE',A2.DocEntry AS 'PO_#',
			U_landedcost AS 'LANDEDCOST' FROM POR1 A2
			INNER JOIN OPOR A3 ON A2.DocEntry=A3.DocNum
			WHERE A2.BaseType=540000006  AND A3.CANCELED='N'
			AND A2.ITEMCODE IS NOT NULL
			AND A2.DOCENTRY NOT IN (SELECT T.BASEENTRY FROM PCH1 T INNER JOIN OPCH TT ON T.DocEntry=TT.DOCNUM WHERE T.BaseType=22 AND CANCELED='N' AND ITEMCODE IS NOT NULL)
			UNION ALL
			SELECT DISTINCT A3.INMPrice,A3.DocEntry,A0.BaseEntry,A3.Quantity,A3.ItemCode,A3.WhsCode,A3.ObjType,A4.TAXDATE, 'AP'AS 'RTYPE',a0.DocEntry AS 'PO_#',
			0  AS 'LANDEDCOST' FROM POR1 A0 
			INNER JOIN PCH1 A3 ON A0.DocEntry=A3.BaseEntry
			INNER JOIN OPCH A4 ON A3.DocEntry=A4.DocNum
			WHERE A3.BaseType=22  AND A4.CANCELED='N'
			AND A3.DocEntry NOT IN (SELECT DocEntry FROM PCH21 WHERE RefObjType=13)
			AND A3.ITEMCODE IS NOT NULL
			UNION ALL
			SELECT DISTINCT A3.INMPrice,A3.DocEntry,A0.BaseEntry,A3.Quantity,A3.ItemCode,A3.WhsCode,A3.ObjType,A4.TAXDATE, 'AP'AS 'RTYPE',a3.docentry,0 AS 'LANDEDCOST'  FROM PRQ1 A0 
			INNER JOIN PQT1 A1 ON A0.DocEntry=A1.BaseEntry
			INNER JOIN POR1 A2 ON A1.DocEntry=A2.BaseEntry
			INNER JOIN PCH1 A3 ON A2.DocEntry=A3.BaseEntry
			INNER JOIN OPCH A4 ON A3.DocEntry=A4.DocNum
			WHERE A3.BaseType=22  AND A4.CANCELED='N'
			AND A3.ITEMCODE IS NOT NULL
			UNION ALL
			SELECT DISTINCT A2.INMPrice,A2.DocEntry,A0.BaseEntry,A2.Quantity,A2.ItemCode,A2.WhsCode,A2.ObjType,A3.TAXDATE,'PO'AS 'RTYPE',a2.DocEntry AS 'PO_#',
			U_landedcost AS 'LANDEDCOST' FROM PRQ1 A0 
			INNER JOIN PQT1 A1 ON A0.DocEntry=A1.BaseEntry
			INNER JOIN POR1 A2 ON A1.DocEntry=A2.BaseEntry
			INNER JOIN OPOR A3 ON A2.DocEntry=A3.DocNum
			WHERE A2.BaseType=540000006  AND A3.CANCELED='N'
			AND A2.ITEMCODE IS NOT NULL
			AND A2.DOCENTRY NOT IN (SELECT T.BASEENTRY FROM PCH1 T INNER JOIN OPCH TT ON T.DocEntry=TT.DOCNUM WHERE T.BaseType=22 AND CANCELED='N' AND ITEMCODE IS NOT NULL)
			)AS T5
			ON T5.BaseEntry=T0.BaseEntry
			AND T5.ItemCode=T0.ItemCode --AND T5.WhsCode=T0.WhsCode
--SO TO AP WITH BROKEN LINK REFERENCED THRU PURCHASE REQUEST
LEFT JOIN (SELECT DISTINCT A0.DOCENTRY,A4.RefObjType,A4.REFDOCNUM,A4.DOCENTRY AS 'REF_ENTRY',A4.ISSUEDATE,A0.INMPrice,A0.ItemCode,A0.ObjType,A0.Quantity,'PO'AS 'RTYPE', 0 AS 'LANDEDCOST' FROM PCH1 A0
		INNER JOIN POR1 A1 ON A0.BaseEntry=A1.DocEntry
		INNER JOIN PQT1 A2 ON A1.BaseEntry=A2.DocEntry
		INNER JOIN PRQ1 A3 ON A2.BaseEntry=A3.DocEntry
		INNER JOIN RDR21 A4 ON A3.DocEntry=A4.RefDocNum
		INNER JOIN OPCH A5 ON A5.DOCNUM=A0.DOCENTRY
		WHERE A4.RefObjType=1470000113 AND A5.CANCELED='N'
		UNION ALL
		SELECT DISTINCT A0.DOCENTRY,A3.RefObjType,A3.REFDOCNUM,A3.DOCENTRY AS 'REF_ENTRY',A3.ISSUEDATE,A0.INMPrice,A0.ItemCode,A0.ObjType,A0.Quantity,'PO'AS 'RTYPE',
			U_landedcost AS 'LANDEDCOST' FROM POR1 A0
		INNER JOIN PQT1 A1 ON A0.BaseEntry=A1.DocEntry
		INNER JOIN PRQ1 A2 ON A1.BaseEntry=A2.DocEntry
		INNER JOIN RDR21 A3 ON A2.DocEntry=A3.RefDocNum
		INNER JOIN OPOR A4 ON A3.DOCENTRY=A4.DOCNUM
		WHERE A3.RefObjType=1470000113 AND A4.CANCELED='N'
		AND A0.DOCENTRY NOT IN (SELECT T.BASEENTRY FROM PCH1 T INNER JOIN OPCH TT ON T.DocEntry=TT.DOCNUM WHERE T.BaseType=22 AND CANCELED='N' AND ITEMCODE IS NOT NULL)) 
		AS T6
		ON T0.BaseEntry=T6.REF_ENTRY AND T6.ItemCode=T0.ItemCode
--SO TO AP WITH BROKEN LINK REFERENCED THRU PURCHASE ORDER
LEFT JOIN (SELECT DISTINCT A0.DOCENTRY,A3.RefObjType,A3.REFDOCNUM,A3.DOCENTRY AS 'REF_ENTRY',A3.ISSUEDATE,A0.INMPrice,A0.ItemCode,A0.ObjType,A0.Quantity,'AP'AS 'RTYPE',
			0 AS 'LANDEDCOST' FROM POR1 A0
		INNER JOIN RDR21 A3 ON A0.DocEntry=A3.RefDocNum
		INNER JOIN OPOR A4 ON A3.RefDocNum=A4.DOCNUM
		inner join pch1 a5 on a0.DocEntry=a5.BaseEntry
		inner join opch a6 on a5.DocEntry=a6.DocNum
		WHERE A3.RefObjType=22 AND A6.CANCELED='N'
		
		union all
		SELECT DISTINCT A0.DOCENTRY,A3.RefObjType,A3.REFDOCNUM,A3.DOCENTRY AS 'REF_ENTRY',A3.ISSUEDATE,A0.INMPrice,A0.ItemCode,A0.ObjType,A0.Quantity,'PO'AS 'RTYPE',
			U_landedcost AS 'LANDEDCOST' FROM POR1 A0
		INNER JOIN RDR21 A3 ON A0.DocEntry=A3.RefDocNum
		INNER JOIN OPOR A4 ON A3.DOCENTRY=A4.DOCNUM
		WHERE A3.RefObjType=22 AND A4.CANCELED='N'
		AND A0.DOCENTRY NOT IN (SELECT T.BASEENTRY FROM PCH1 T INNER JOIN OPCH TT ON T.DocEntry=TT.DOCNUM WHERE T.BaseType=22 AND CANCELED='N' AND ITEMCODE IS NOT NULL)) 
		AS T7
		ON T0.BaseEntry=T7.REF_ENTRY AND T7.ItemCode=T0.ItemCode
--SO TO AP WITH BROKEN LINK REFERENCED THRU AP INV
LEFT JOIN (SELECT DISTINCT A0.DOCENTRY,A4.RefObjType,A4.REFDOCNUM,A4.DOCENTRY AS 'REF_ENTRY',A5.TaxDate,A0.INMPrice,A0.ItemCode,A0.ObjType,A0.Quantity FROM PCH1 A0
		INNER JOIN PCH21 A4 ON A0.DocEntry=A4.DocEntry
		INNER JOIN OPCH A5 ON A5.DOCNUM=A0.DOCENTRY
		WHERE A4.RefObjType=13 AND A5.CANCELED='N' AND A5.DocType='I') 
		AS T8
		ON T0.DocEntry=T8.REFDOCNUM AND T0.ItemCode=T8.ItemCode
--LANDED COST
LEFT JOIN (SELECT  A0.DOCENTRY,A1.REFDOCNUM,A0.DocTotal-ISNULL(SUM(A3.DocTotal),0) AS 'LANDEDCOST',A2.Number FROM OPCH A0
		INNER JOIN PCH21 A1 ON A0.DOCNUM=A1.DocEntry
		INNER JOIN OJDT A2 ON A0.DocNum=A2.BaseRef AND TransType=18
		LEFT JOIN (SELECT TT.BaseEntry,DocTotal
			FROM ORPC T INNER JOIN RPC1 TT ON T.DocNum=TT.DocEntry 
			WHERE TT.BaseType=18
			)AS A3 ON A0.DocNum=A3.BaseEntry
		WHERE A1.RefObjType=13 AND A0.CANCELED='N' AND A0.DocType='S'
		GROUP BY A0.DOCENTRY,A1.RefObjType,A1.REFDOCNUM,A1.DOCENTRY,A0.DocTotal,A2.Number) 
		AS T9
		ON T0.DocEntry=T9.REFDOCNUM 
--JE
INNER JOIN OJDT T10 ON T0.DocEntry=T10.BaseRef AND T10.TransType =13
LEFT JOIN (SELECT A1.QUANTITY,A1.ITEMCODE,A0.RefDocNum FROM IGE21 A0
		INNER JOIN IGE1 A1 ON A0.DOCENTRY=A1.DOCENTRY
		WHERE A0.REFOBJTYPE =13) 
		AS T11 ON T11.REFDOCNUM=T0.DOCENTRY AND T11.ITEMCODE=T0.ITEMCODE
INNER JOIN (SELECT  DOCENTRY,SUM(A2.INMPrice*(A2.Quantity-ISNULL(A3.Quantity,0))) AS 'SALES SUM' FROM INV1 A2 
		LEFT JOIN (SELECT B1.QUANTITY,REFDOCNUM,B1.ItemCode FROM IGE21 B0
					INNER JOIN IGE1 B1 ON B0.DOCENTRY=B1.DOCENTRY
					WHERE B0.REFOBJTYPE =13)
					AS A3 ON A2.DocEntry=A3.REFDOCNUM AND A2.ItemCode=A3.ItemCode
		GROUP BY DOCENTRY)
		AS T12 ON T0.DocEntry=T12.DocEntry

WHERE T3.DocType = 'I' 
AND T1.ItemType <> 'F'
AND T3.DocDate >= @DATEFROM AND T3.DocDate <= @DATETO
AND T3.CANCELED='N'
AND T3.ISINS='N'
AND  T3.U_BO_DRS ='Y' --OR T3.U_BO_DSDD ='Y' OR T3.U_BO_DSDV ='Y' OR T3.U_BO_DSPD ='Y' 


) D
LEFT JOIN OJDT ON OJDT.BaseRef=D.[DE-AP] AND OJDT.TransType = D.TRANSTYPE
WHERE 
D.[Quantity Sold]<>0
-- AND D.[BRANCH ID] NOT IN (SELECT BPLId FROM OBPL WHERE U_isDC='Y')
AND D.Department LIKE '%'+@DEPARTMENT+'%' 
AND D.Category LIKE '%'+@CATEGORY+'%'
AND D.Description LIKE '%'+@ITEMNAME+'%'
AND D.Whse LIKE '%'+@STORE+'%'
AND D.CANCELED='N'
ORDER BY 'Transaction#' ASC



