select SUM(QTY*WEIGHT_PER_PIECE) from TBL_DLVRY_DETAILS WHERE DLVR_ID=2344

SELECT * FROM tbl_delivery WHERE DLVRY_ID=2344

UPDATE tbl_delivery SET TOTAL_WEIGHT=(select SUM(QTY*WEIGHT_PER_PIECE) from TBL_DLVRY_DETAILS WHERE DLVR_ID=DLVRY_ID)


UPDATE TBL_DLVRY_DETAILS SET TOTAL_WEIGHT=QTY*WEIGHT_PER_PIECE 