/* SELECT T2.DOCNUM,unitMsr,unitMsr2, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=01 */


specific item

--SELECT 'AR' AS 'TYPE', T2.DOCNUM,YEAR(TaxDate) as Year,t1.UomCode,UomCode2,ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
--ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
--FROM INV1 T1
--INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
--WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
----AND T2.TaxDate LIKE '%2021%'
----AND UomCode LIKE'%PR%'
--AND ITEMCODE ='0005777HWSPL'

--UNION ALL

--SELECT 'ARCM' AS 'TYPE',T2.DOCNUM,YEAR(TaxDate) as Year,t1.UomCode,UomCode, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
--ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
--FROM RIN1 T1
--INNER JOIN ORIN T2 ON T1.DocEntry=T2.DocNum
--WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
----AND T2.TaxDate LIKE '%2021%'
----AND UomCode LIKE'%PR%'
--AND ITEMCODE ='0005777HWSPL'
--ORDER BY TaxDate





 SELECT  ItemCode,(SELECT TOP 1 ItemName FROM OITM WHERE ItemCode=X.ITEMCODE) AS 'DESCRIPTION',[SMALLEST UNIT], 
 sum(Quantity) as 'QTY',sum(Quantity)/12 AS 'AVG SOLD',(SELECT FACTOR FROM ITM1 WHERE PriceList=12 AND ItemCode=X.ItemCode) AS 'FACTOR'
--SELECT ItemCode,(SELECT TOP 1 ItemName FROM OITM WHERE ItemCode=X.ITEMCODE) AS 'DESCRIPTION',MAX(Quantity) as Quantity, (SELECT FACTOR FROM ITM1 WHERE PriceList=12 AND ItemCode=X.ItemCode) AS 'FACTOR'
--(
--SELECT CONCAT (',' , (SELECT X = STUFF((
--         SELECT 
--		' '+MONTH(TAXDATE)
--		FROM INV1 T1
--INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
--WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
--AND T2.TaxDate LIKE '%2021%'
--AND ItemCode=X.ItemCode AND MONTH(TAXDATE)=X.MONTH

--            FOR XML PATH('')
--         ), 1, 1, '')))  
--)

 FROM(
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=01
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=02
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=03
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=04
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=05
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=06
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=07
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=08
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=09
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=10
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=11
UNION ALL
SELECT T2.DOCNUM, ItemCode,unitMsr2 AS 'SMALLEST UNIT',Quantity*NumPerMsr AS 'Quantity',TAXDATE,
ROW_NUMBER() OVER (PARTITION BY ItemCode ORDER BY Quantity DESC) rank
FROM INV1 T1
INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum
WHERE ItemCode IS NOT NULL AND T2.CANCELED ='N'
AND T2.TaxDate LIKE '%2021%'
AND MONTH(TAXDATE)=12
) X
WHERE X.rank = 1 
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=1 AND T2.TaxDate LIKE '%2021%' AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=2 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=3 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=4 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=5 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=6 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=7 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=8 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=9 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=10 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=11 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
AND ItemCode IN (SELECT ItemCode FROM INV1 T1 INNER JOIN OINV T2 ON T1.DocEntry=T2.DocNum AND T2.CANCELED='N'WHERE  MONTH(TaxDate)=12 AND T2.TaxDate LIKE '%2021%'AND ItemCode=X.ItemCode)
GROUP by ItemCode ,[SMALLEST UNIT]

ORDER BY ItemCode--,[MONTH]