DECLARE @TYPE INT= 0

IF (@TYPE =0)

select T.* from(

select
T0.Docdate as 'document date',
t0.taxdate,

CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '01'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '04'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '07'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '10'
ELSE 'N/A'
END AS WtaxMonthFrom,
'01' as WTaxDayFrom,
CONVERT(varchar(10), year(T0.taxdate))  as 'WtaxYearFrom',

CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '03'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '06'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '09'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '12'
ELSE 'N/A'
END AS WtaxMonthTo,
CONVERT(varchar(10), DAY(EOMONTH(
CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '2020-03-20 00:00:00.000'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '2020-06-20 00:00:00.000'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '2020-09-20 00:00:00.000'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '2020-12-20 00:00:00.000'
ELSE 'N/A' END
))) as WTaxDayTo,
CONVERT(varchar(10), year(t0.taxdate))  as 'WtaxYearTo',

T0.CardCode ,
CASE 
WHEN T0.U_ALIAS_VENDOR IS NULL THEN T0.CardName
ELSE T0.U_ALIAS_VENDOR
END AS 'Payee',
T0.DocDate , 
CASE 
WHEN T0.U_TIN IS NOT NULL THEN LEFT(T0.U_TIN,3)
ELSE (SELECT LEFT(LicTradNum, 3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) END As 'P1stTIN',
CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,5,3)
ELSE (SELECT SUBSTRING(LicTradNum,5,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) END As 'P2ndTIN',
CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,9,3)
ELSE (SELECT SUBSTRING(LicTradNum,9,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) END As 'P3rdTIN',
CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,13,3)
ELSE (SELECT SUBSTRING(LicTradNum,13,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) END As 'P4thTIN',  
T0.DocTotal, 
(SELECT TaxbleAmnt FROM PCH5 T1 WHERE T0.DocNum = T1.AbsEntry) AS 'TaxbleAmnt',
T0.WTSum, T0.U_WTax,  

(SELECT TOP 1 TI.U_ATCDesc FROM OWHT TI 
INNER JOIN PCH5 T1 ON  TI.WTCode = T1.WTCode WHERE  T1.AbsEntry =T0.DocNum ) AS 'ATC Description', 
CASE 
WHEN T0.U_ADDRESS IS NOT NULL THEN T0.U_ADDRESS
ELSE
UPPER((SELECT DISTINCT CONCAT(CAST(Building AS varchar(max)),
(CASE WHEN Building IS NULL THEN '' ELSE ' ' END),Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END), StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],
(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) 
FROM CRD1 WHERE CardCode = t0.CardCode AND AdresType = 'B')) END AS 'Payee Address',
CASE 
WHEN T0.U_ADDRESS IS NOT NULL THEN T0.U_ZIPCODE
ELSE
(SELECT DISTINCT ZipCode FROM CRD1 WHERE CardCode = T0.CardCode AND AdresType = 'B') END AS 'PayeeZipCode',

(Select CompnyName from OADM) AS 'Payor',

CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '423'
ELSE 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END AS 'PY1stTIN',

CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '256'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
 END AS 'PY2ndTIN',

 CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '513'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END AS 'PY3ndTIN',

CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1  SUBSTRING(FedTaxId,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '001'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1  SUBSTRING(FedTaxId,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
 END AS 'PY4thTIN',



CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum) )) 
WHEN T0.DOCTYPE = 'S' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(
SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum) )) END IS NULL THEN 'CORNER OSITA, ZONE II, LOT NO. 23-A, GENERAL SANTOS DRIVE, KORONADAL CITY '
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum) )) 
WHEN T0.DOCTYPE = 'S' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(
SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum) )) END 
 END   AS 'PayorAddress',

 
CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT  TOP 1  OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '9506'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT  TOP 1  OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END  AS 'PayorZipCode',


(SELECT COUNT(*) from VPM2 T6 WHERE T6.DOCNUM =1821) AS 'ROWS',
t0.ReceiptNum as doc
FROM OPCH T0 
INNER JOIN VPM2 T3 ON T0.Docentry = T3.Docentry
INNER JOIN OVPM T4 ON  T0.ReceiptNum=T4.DocNum
WHERE T3.DocNum = 1821
AND T0.CANCELED='N'
--------////END OF OPCH
UNION

select
T0.Docdate as 'document date',
t0.taxdate,

CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '01'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '04'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '07'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '10'
ELSE 'N/A'
END AS WtaxMonthFrom,
'01' as WTaxDayFrom,
CONVERT(varchar(10), year(T0.taxdate))  as 'WtaxYearFrom',

CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '03'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '06'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '09'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '12'
ELSE 'N/A'
END AS WtaxMonthTo,
CONVERT(varchar(10), DAY(EOMONTH(
CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '2020-03-20 00:00:00.000'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '2020-06-20 00:00:00.000'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '2020-09-20 00:00:00.000'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '2020-12-20 00:00:00.000'
ELSE 'N/A' END
))) as WTaxDayTo,
CONVERT(varchar(10), year(t0.taxdate))  as 'WtaxYearTo',

T0.CardCode ,
CASE 
WHEN T0.U_ALIAS_VENDOR IS NULL THEN T0.CardName
ELSE T0.U_ALIAS_VENDOR
END AS 'Payee',
T0.DocDate , 
CASE 
WHEN T0.U_TIN IS NOT NULL THEN LEFT(T0.U_TIN,3)
ELSE (SELECT LEFT(LicTradNum, 3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) END As 'P1stTIN',
CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,5,3)
ELSE (SELECT SUBSTRING(LicTradNum,5,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) END As 'P2ndTIN',
CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,9,3)
ELSE (SELECT SUBSTRING(LicTradNum,9,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) END As 'P3rdTIN',
CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,13,3)
ELSE (SELECT SUBSTRING(LicTradNum,13,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) END As 'P4thTIN',  
T0.DocTotal, 
(SELECT TaxbleAmnt FROM PCH5 T1 WHERE T0.DocNum = T1.AbsEntry) AS 'TaxbleAmnt',
T0.WTSum, T0.U_WTax,  

(SELECT TOP 1 TI.U_ATCDesc FROM OWHT TI 
INNER JOIN PCH5 T1 ON  TI.WTCode = T1.WTCode WHERE  T1.AbsEntry =T0.DocNum ) AS 'ATC Description', 
CASE 
WHEN T0.U_ADDRESS IS NOT NULL THEN T0.U_ADDRESS
ELSE
UPPER((SELECT DISTINCT CONCAT(CAST(Building AS varchar(max)),
(CASE WHEN Building IS NULL THEN '' ELSE ' ' END),Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END), StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],
(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) 
FROM CRD1 WHERE CardCode = t0.CardCode AND AdresType = 'B')) END AS 'Payee Address',
CASE 
WHEN T0.U_ADDRESS IS NOT NULL THEN T0.U_ZIPCODE
ELSE
(SELECT DISTINCT ZipCode FROM CRD1 WHERE CardCode = T0.CardCode AND AdresType = 'B') END AS 'PayeeZipCode',

(Select CompnyName from OADM) AS 'Payor',

CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '423'
ELSE 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END AS 'PY1stTIN',

CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '256'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
 END AS 'PY2ndTIN',

 CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '513'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END AS 'PY3ndTIN',

CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1  SUBSTRING(FedTaxId,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '001'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1  SUBSTRING(FedTaxId,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
 END AS 'PY4thTIN',



CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum) )) 
WHEN T0.DOCTYPE = 'S' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(
SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum) )) END IS NULL THEN 'CORNER OSITA, ZONE II, LOT NO. 23-A, GENERAL SANTOS DRIVE, KORONADAL CITY '
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum) )) 
WHEN T0.DOCTYPE = 'S' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(
SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum) )) END 
 END   AS 'PayorAddress',

 
CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT  TOP 1  OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '9506'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT  TOP 1  OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END  AS 'PayorZipCode',


99 AS 'ROWS',

t0.DOCENTRY as doc
 FROM ODPO T0
 INNER JOIN DPO1 T1 ON T0.DocNum=T1.DOCENTRY
 INNER JOIN VPM2 T3 ON T0.Docentry = T3.Docentry
 WHERE T3.docnum =1821
 AND T0.CANCELED='N'
------///END ODPO
 )T
WHERE T.WTSum>0
ORDER BY T.DOC ASC
OFFSET 0 ROWS FETCH NEXT 15 ROWS ONLY


ELSE

select
T0.Docdate as 'document date',
t0.taxdate,

CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '01'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '04'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '07'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '10'
ELSE 'N/A'
END AS WtaxMonthFrom,
'01' as WTaxDayFrom,
CONVERT(varchar(10), year(T0.taxdate))  as 'WtaxYearFrom',

CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '03'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '06'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '09'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '12'
ELSE 'N/A'
END AS WtaxMonthTo,
CONVERT(varchar(10), DAY(EOMONTH(
CASE
WHEN
month(t0.taxdate) = '1' OR month(t0.taxdate)= '2' OR month(t0.taxdate)= '3' THEN '2020-03-20 00:00:00.000'
WHEN
month(t0.taxdate) = '4' OR month(t0.taxdate)= '5' OR month(t0.taxdate)= '6' THEN '2020-06-20 00:00:00.000'
WHEN
month(t0.taxdate) = '7' OR month(t0.taxdate)= '8' OR month(t0.taxdate)= '9' THEN '2020-09-20 00:00:00.000'
WHEN
month(t0.taxdate) = '10' OR month(t0.taxdate)= '11' OR month(t0.taxdate)= '12' THEN '2020-12-20 00:00:00.000'
ELSE 'N/A' END
))) as WTaxDayTo,
CONVERT(varchar(10), year(t0.taxdate))  as 'WtaxYearTo',

T0.CardCode ,T0.CardName, T0.DocDate , 
(SELECT LEFT(LicTradNum, 3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) As 'P1stTIN',
(SELECT SUBSTRING(LicTradNum,5,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) As 'P2ndTIN',
(SELECT SUBSTRING(LicTradNum,9,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) As 'P3rdTIN',
(SELECT SUBSTRING(LicTradNum,13,3) FROM OCRD TT WHERE TT.CardCode = T0.CardCode) As 'P4thTIN', 
T0.DocTotal, 
(SELECT TaxbleAmnt FROM PCH5 T1 WHERE T0.DocNum = T1.AbsEntry) AS 'TaxbleAmnt',
T0.WTSum, T0.U_WTax,  

(SELECT TOP 1 TI.U_ATCDesc FROM OWHT TI 
INNER JOIN PCH5 T1 ON  TI.WTCode = T1.WTCode WHERE  T1.AbsEntry =T0.DocNum ) AS 'ATC Description', 
UPPER((SELECT DISTINCT CONCAT(CAST(Building AS varchar(max)),
(CASE WHEN Building IS NULL THEN '' ELSE ' ' END),Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END), StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],
(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) 
FROM CRD1 WHERE CardCode = t0.CardCode AND AdresType = 'B')) AS 'Payee Address',

CASE 
WHEN T0.U_ALIAS_VENDOR IS NULL THEN (Select CompnyName from OADM)
ELSE T0.U_ALIAS_VENDOR
END AS 'Payor',

CASE 
WHEN T0.U_TIN IS NOT NULL THEN LEFT(T0.U_TIN,3)
ELSE
CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '423'
ELSE 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 Left(FedTaxID,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END END AS 'PY1stTIN',

CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,5,3)
ELSE
CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '256'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,5,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
 END END AS 'PY2ndTIN',

CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,9,3)
ELSE
 CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '513'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1 SUBSTRING(FedTaxId,9,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END END AS 'PY3ndTIN',

CASE 
WHEN T0.U_TIN IS NOT NULL THEN SUBSTRING(T0.U_TIN,13,3)
ELSE
CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1  SUBSTRING(FedTaxId,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '001'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(Select TOP 1 SUBSTRING(FedTaxID,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(Select TOP 1  SUBSTRING(FedTaxId,13,3) FROM OWHS WHERE WhsCode=(SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
 END END AS 'PY4thTIN',




CASE 
WHEN T0.U_ADDRESS IS NOT NULL THEN T0.U_ADDRESS
ELSE
 CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum) )) 
WHEN T0.DOCTYPE = 'S' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(
SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum) )) END IS NULL THEN 'CORNER OSITA, ZONE II, LOT NO. 23-A, GENERAL SANTOS DRIVE, KORONADAL CITY '
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum) )) 
WHEN T0.DOCTYPE = 'S' THEN
UPPER((SELECT TOP 1 CONCAT(CAST(Building AS varchar(max)),(CASE WHEN Building IS NULL THEN '' ELSE ', ' END),
Street,(CASE WHEN Street IS NULL THEN '' ELSE ', ' END),StreetNo,(CASE WHEN StreetNo IS NULL THEN '' ELSE ', ' END),[Block],(CASE WHEN [Block] IS NULL THEN '' ELSE ', ' END),
City,(CASE WHEN City IS NULL THEN '' ELSE ' ' END)) FROM owhs  WHERE WhsCode=(
SELECT TOP 1 OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum) )) END 
 END  END AS 'PayorAddress',

 CASE 
WHEN T0.U_ADDRESS IS NOT NULL THEN T0.U_ZIPCODE
ELSE
 CASE WHEN 
CASE WHEN T0.DOCTYPE = 'I' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT  TOP 1  OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END IS NULL THEN '9506'
ELSE
CASE WHEN T0.DOCTYPE = 'I' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT TOP 1 WhsCode FROM PCH1 WHERE DocEntry=T0.DocNum))
WHEN T0.DOCTYPE = 'S' THEN
(SELECT TOP 1 ZipCode FROM owhs  WHERE WhsCode=(SELECT  TOP 1  OOCR.U_Whse FROM PCH1 
INNER JOIN OOCR ON PCH1.OCRCODE = OOCR.OCRCODE WHERE DocEntry=T0.DocNum)) END
END END AS 'PayorZipCode',

( SELECT DISTINCT ZipCode FROM CRD1 WHERE CardCode = T0.CardCode AND AdresType = 'B') AS 'PayeeZipCode',
1 AS 'ROWS',
t0.ReceiptNum as doc
FROM OPCH T0 
WHERE T0.DocNum = 1821
